### ISSUE TITLE
Cannot find MSAL/Msal.H

### ISSUE THREAD

**Issue by alcantaramark** [wrobins/cordova-plugin-msal#49]
Hello, having some issues when used this plugin. I cannot run on Xcode saying that MSAL/Msal.h is not found on the import. Thanks!

**Comment by fatbone008** [comment]
the same problem

**Comment by jeffortdev** [comment]
I used cordova 10 and cordova-ios 5.1.1 to resolve that error.

**Comment by fchamieh** [comment]
> I used cordova 10 and cordova-ios 5.1.1 to resolve that error.

same here, resolved with cordova 10, cordova ios ^6

**Comment by keshavvvv19** [comment]
Could you please help am getting msal.h file not found. Is it mandatory to use cordova10 or is there any other way to resolve it

**Comment by jeffortdev** [comment]
> Could you please help am getting msal.h file not found. Is it mandatory to use cordova10 or is there any other way to resolve it

I don't think there is another way, I've tried this using cordova 9 and got the same error.

**Comment by KiranSuresha** [comment]
Resolved by removing and adding cordova to the project, cordova 10.0.0 and cordova-ios 6.2.0

**Comment by Digital-Chen** [comment]
I upgraded an existing Ionic project to cordova 10 and cordova-ios 6.2 but I still don't find MSAL.h. Any suggestion?

**Comment by jeffortdev** [comment]
> I upgraded an existing Ionic project to cordova 10 and cordova-ios 6.2 but I still don't find MSAL.h. Any suggestion?

remove the platform, then add again.

**Comment by Aston13** [comment]
> I upgraded an existing Ionic project to cordova 10 and cordova-ios 6.2 but I still don't find MSAL.h. Any suggestion?

I am having the same issue, anyone found a solution?

Have updated to Cordova@latest and cordova-ios@latest, removed/added the platform, cordova prepare etc. and the issue persists

**Comment by Aston13** [comment]
![image](https://user-images.githubusercontent.com/23441191/111954098-dfb21300-8ae7-11eb-9c34-66f08210b6b9.png)

Does anyone else have this output from CocoaPods after install? possibly could be related

**Comment by Digital-Chen** [comment]
> ![image](https://user-images.githubusercontent.com/23441191/111954098-dfb21300-8ae7-11eb-9c34-66f08210b6b9.png)
> 
> Does anyone else have this output from CocoaPods after install? possibly could be related

In my case, I had ms-adal in the project and apparently it caused conflict. I couldn't remove it by uninstall command so I manually deleted it from node modules, and then reinstall cordova-ios. The error suddenly went away. There were a couple of other steps I took in the generated project but I am sure you can figure those out easily.

**Comment by Aston13** [comment]
The issue is fixed for me now, it was because I was opening the .xcodeproj and not the .xcworkspace! took me too long to figure that out :'D

**Comment by exlmobility** [comment]
> The issue is fixed for me now, it was because I was opening the .xcodeproj and not the .xcworkspace! took me too long to figure that out :'D

hi can you please tell me which version of ios and cordova you are using

**Comment by exlmobility** [comment]
> The issue is fixed for me now, it was because I was opening the .xcodeproj and not the .xcworkspace! took me too long to figure that out :'D

hi can you please tell me which version of ios and cordova you are using
